### ISSUE TITLE
Block HTTP connections by default

### ISSUE THREAD

**Issue by flawedworld** [flawedworld/Hexavalent#15]

**Comment by Seirdy** [comment]
Built-in Chromium feature:

1. Enable HTTPS-First mode in `chrome://flags`
2. Settings -> Privacy & Security -> Security -> Always use secure connections

Hexavalent should set this by default.

**Comment by flawedworld** [comment]
94 shipped the toggle, need to make it the default.

**Comment by qua3k** [comment]
> 94 shipped the toggle, need to make it the default.

We can do this by changing https://github.com/chromium/chromium/blob/2d4b8e3a8b8e59d91265ff47c0402ecccd14233b/chrome/browser/ui/browser_ui_prefs.cc#L163
