### ISSUE TITLE
Disable autofill for mixed HTTP forms on HTTPS sites

### ISSUE THREAD

**Issue by flawedworld** [flawedworld/Hexavalent#20]

**Comment by qua3k** [comment]
This is default behavior in Chromium.

**Comment by qua3k** [comment]
https://github.com/chromium/chromium/blob/5ad027716bb9aeeb64be61b3fb3590f2d3498b3c/components/autofill/core/common/autofill_features.cc#L295

**Comment by qua3k** [comment]
You can see it in action on https://www.mixedcontentexamples.com/Test/NonSecureForm
